<?php

namespace Modules\Exercise04\Tests\Feature\Http\Controllers;

use Carbon\Carbon;
use Modules\Exercise04\Http\Controllers\CalendarController;
use Modules\Exercise04\Services\CalendarService;
use Tests\TestCase;

class CalendarControllerTest extends TestCase
{
    protected $calendarService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calendarService = \Mockery::mock(CalendarService::class);
    }

    public function testIndex()
    {
        $this->calendarService
            ->shouldReceive('getDateClass')
            ->with(Carbon::parse('2020-09-01'), ['2020-09-26'])
            ->andReturn(CalendarService::COLOR_BLACK);
        $response = $this->get(action([CalendarController::class, 'index']));
        $response->assertViewIs('exercise04::calendar');
    }
}
