<?php

namespace Modules\Exercise02\Tests\Unit\Http\Requests;

use Illuminate\Support\Facades\Validator;
use Modules\Exercise02\Http\Requests\ATMRequest;
use Modules\Exercise02\Models\ATM;
use Tests\SetupDatabaseTrait;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ATMRequestTest extends TestCase
{
    use RefreshDatabase;

    protected $request;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = new ATMRequest();
    }

    public function test_card_id_valid()
    {
        $input = [
            'card_id' => 1,
        ];
        ATM::factory()->create($input);

        $validator = Validator::make($input, $this->request->rules());
        $this->assertTrue($validator->passes());
    }

    public function test_card_id_invalid_required()
    {
        $input = [
            'card_id' => '',
        ];

        $validator = Validator::make($input, $this->request->rules());
        $this->assertFalse($validator->passes());
    }

    public function test_card_id_invalid_in_atms_table()
    {
        $input = [
            'card_id' => -1,
        ];

        ATM::factory()->create();

        $validator = Validator::make($input, $this->request->rules());
        $this->assertFalse($validator->passes());
    }
}
