<?php

namespace Modules\Exercise04\Tests\Unit\Services;

use Carbon\Carbon;
use Modules\Exercise04\Services\CalendarService;
use Tests\TestCase;

class CalendarServiceTest extends TestCase
{
    protected $calendarService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calendarService = app()->make(CalendarService::class);
    }

    /**
     * @param Carbon $date
     *
     *  @param array $holidays
     *  @param $result
     *
     * @dataProvider providerTestGetDateClass
     */
    public function testGetDateClass($date, $holidays, $result)
    {
        $response = $this->calendarService->getDateClass($date, $holidays);
        $this->assertEquals($result, $response);
    }

    public function providerTestGetDateClass()
    {
        return [
            [Carbon::parse('2021-04-04'), [], CalendarService::COLOR_RED],
            [Carbon::parse('2021-04-03'), [], CalendarService::COLOR_BLUE],
            [Carbon::parse('2021-04-02'), ['2021-04-02'], CalendarService::COLOR_RED],
        ];
    }
}
