<?php

namespace Modules\Exercise08\Tests\Unit\Services;

use Carbon\Carbon;
use InvalidArgumentException;
use Modules\Exercise08\Services\TicketService;
use Tests\TestCase;

class TicketServiceTest extends TestCase
{
    protected $ticketServiceMock;
    protected $date;
    protected $tuesday;
    protected $friday;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ticketServiceMock = new TicketService();
        $this->date = Carbon::parse('first monday of this month')->format('m/d/Y');
        $this->tuesday = Carbon::parse('first tuesday of this month')->format('m/d/Y');
        $this->friday = Carbon::parse('first friday of this month')->format('m/d/Y');
    }

    public function test_age_less_than_min()
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('The age must be from ' . TicketService::MIN_AGE . ' to ' . TicketService::MAX_AGE);
        $input = [
            'name' => 'Quan',
            'age' => -1,
            'gender' => 'male',
            'booking_date' => $this->date,
        ];

        $this->ticketServiceMock->calculatePrice($input);
    }

    public function test_age_equals_than_min()
    {
        $input = [
            'name' => 'Quan',
            'age' => 0,
            'gender' => 'male',
            'booking_date' => $this->date,
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_age_greater_than_max()
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('The age must be from ' . TicketService::MIN_AGE . ' to ' . TicketService::MAX_AGE);
        $input = [
            'name' => 'Quan',
            'age' => 121,
            'gender' => 'male',
            'booking_date' => $this->date,
        ];

        $this->ticketServiceMock->calculatePrice($input);
    }

    public function test_age_equals_than_max()
    {
        $input = [
            'name' => 'Quan',
            'age' => 120,
            'gender' => 'male',
            'booking_date' => $this->date,
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_OVER_65, $fee);
    }

    public function test_age_12_year_old()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'gender' => 'male',
            'booking_date' => $this->date,
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_booking_date_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'gender' => 'male',
            'booking_date' => $this->tuesday,
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_male_12_year_old()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'booking_date' => $this->date,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_male_13_year_old()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'booking_date' => $this->date,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE, $fee);
    }

    public function test_male_12_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'booking_date' => $this->tuesday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_male_13_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'booking_date' => $this->tuesday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_male_65_year_old_on_monday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 65,
            'booking_date' => $this->date,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE, $fee);
    }

    public function test_male_66_year_old_on_monday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 66,
            'booking_date' => $this->date,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_OVER_65, $fee);
    }

    public function test_male_65_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 65,
            'booking_date' => $this->tuesday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_male_66_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 66,
            'booking_date' => $this->tuesday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_male_12_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'booking_date' => $this->friday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_male_13_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'booking_date' => $this->friday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE, $fee);
    }

    public function test_male_65_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 65,
            'booking_date' => $this->friday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE, $fee);
    }

    public function test_male_66_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 66,
            'booking_date' => $this->friday,
            'gender' => 'male',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_OVER_65, $fee);
    }

    public function test_female_12_year_old_on_monday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'booking_date' => $this->date,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_female_13_year_old_on_monday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'booking_date' => $this->date,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE, $fee);
    }

    public function test_female_12_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'booking_date' => $this->tuesday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_female_13_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'booking_date' => $this->tuesday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_female_65_year_old_on_monday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 65,
            'booking_date' => $this->date,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE, $fee);
    }

    public function test_female_66_year_old_on_monday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 66,
            'booking_date' => $this->date,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_OVER_65, $fee);
    }

    public function test_female_65_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 65,
            'booking_date' => $this->tuesday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_female_66_year_old_on_tuesday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 66,
            'booking_date' => $this->tuesday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_IN_TUESDAY, $fee);
    }

    public function test_female_12_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 12,
            'booking_date' => $this->friday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::BASE_PRICE * 0.5, $fee);
    }

    public function test_female_13_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 13,
            'booking_date' => $this->friday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_FEMALE_FRIDAY, $fee);
    }

    public function test_female_65_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 65,
            'booking_date' => $this->friday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_FEMALE_FRIDAY, $fee);
    }

    public function test_female_66_year_old_on_friday()
    {
        $input = [
            'name' => 'Quan',
            'age' => 66,
            'booking_date' => $this->friday,
            'gender' => 'female',
        ];

        $fee = $this->ticketServiceMock->calculatePrice($input);
        $this->assertEquals(TicketService::PRICE_FEMALE_FRIDAY, $fee);
    }
}
