<?php

namespace Modules\Exercise04\Tests\Feature\Http\Controllers;

use Modules\Exercise05\Http\Controllers\Exercise05Controller;
use Tests\TestCase;

class Exercise05ControllerTest extends TestCase
{
    protected $orderService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $response = $this->get(action([Exercise05Controller::class, 'index']));
        $response->assertViewIs('exercise05::index');
    }

    /**
     * @param array $inputs Request data
     *
     * @dataProvider providerDataValidateOrderRequestFailed
     */

    public function testOrderRequest($inputs)
    {
        $response = $this->post(action([Exercise05Controller::class, 'store']), $inputs);
        $response->assertStatus(302)
            ->assertSessionHasErrors();
    }

    public function providerDataValidateOrderRequestFailed()
    {
        return [
            [['price' => '']],
            [['price' => 'text']],
            [['option_receive' => '']],
            [['option_receive' => 10]],
            [['option_coupon' => '']],
            [['option_receive' => 10]],
        ];
    }

    /**
     * @param array $params
     *
      * @param array $result
     *
     * @dataProvider providerDataStore
     */

    public function testStore($params, $result)
    {
        $response = $this->post(action([Exercise05Controller::class, 'store']), $params);
        $this->assertEquals($result, $response['resultOrder']);
    }

    public function providerDataStore()
    {
        return [
            [
                ['price' => 1600, 'option_receive' => 1, 'option_coupon' => 1],
                ['price' => 1600, 'discount_pizza' => 'Khuyến mại pizza thứ 2', 'discount_potato' => 'Miễn phí khoai tây']
            ],
            [
                ['price' => 1400, 'option_receive' => 2, 'option_coupon' => 1],
                ['price' => 1120.0, 'discount_pizza' => null, 'discount_potato' => null]
            ],
            [
                ['price' => 1400, 'option_receive' => 2, 'option_coupon' => 2],
                ['price' => 1400, 'discount_pizza' => null, 'discount_potato' => null]
            ],
        ];
    }
}
