<?php

namespace Modules\Exercise02\Tests\Unit\Repositories;

use Illuminate\Database\Eloquent\Collection;
use Modules\Exercise02\Models\ATM;
use Modules\Exercise02\Repositories\ATMRepository;
use Tests\TestCase;

class ATMRepositoryTest extends TestCase
{
    protected $atmModel;
    protected $atmRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->atmModel = \Mockery::mock(ATM::class);
        $this->atmRepository = new ATMRepository($this->atmModel);
    }

    public function test_find()
    {
        $expect = new ATM();
        $this->atmModel
            ->shouldReceive('where->first')
            ->times(1)
            ->andReturn($expect);
        $response = $this->atmRepository->find(1);

        $this->assertEquals($expect, $response);
    }
}
